### ISSUE TITLE
Not Compatible with Bak2topbotm Plugin

### ISSUE THREAD

**Issue by aljawaid** [creecros/Task2pdf#1]
The html for the `Bak2topbotm` plugin shows in the pdf.... any way of hiding it?

![image](https://user-images.githubusercontent.com/10233708/46904527-21810d00-cedd-11e8-95ac-57f561ba14fa.png)

**Comment by creecros** [comment]
Ya, we can use a hook that I removed in task2pdf.

**Comment by aljawaid** [comment]
That is beyond my scope :(

**Comment by creecros** [comment]
I'll take care of it.

**Comment by creecros** [comment]
moved the hook on Bak2topbotm to unused hook in Task2pdf
