### ISSUE TITLE
Can't see image from description in the PDF

### ISSUE THREAD

**Issue by apradoc** [creecros/Task2pdf#10]
When requesting to generate the PDF the images from the description do not appear. I'm using the Greenwing template, maybe some overwriting will generate the bug

**Comment by creecros** [comment]
Example of image in description?

**Comment by apradoc** [comment]
Image in description 
![image in description](https://user-images.githubusercontent.com/92080/71315602-ead74880-2437-11ea-8455-82b035818571.png 'Image in description')

Description in PDF
![Description in PDF](https://user-images.githubusercontent.com/92080/71315617-31c53e00-2438-11ea-8f1f-1e9fac73486b.png 'Description in PDF')

**Comment by creecros** [comment]
If the link generating the image is html and links directly to an actual image, then it will work. If its markdown, it won't work. Dompdf is limited in features and not perfect.
