### ISSUE TITLE
did not work with php 7.3

### ISSUE THREAD

**Issue by Lethert** [creecros/Task2pdf#12]
multiple Errrors at the begin in the pdf File:
<br />
<b>Warning</b>:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in <b>C:\laragon\www\Kanban\plugins\Task2pdf\dompdf\src\Dompdf.php</b> on line <b>610</b><br />
<br />
<b>Warning</b>:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in <b>C:\laragon\www\Kanban\plugins\Task2pdf\dompdf\src\Dompdf.php</b> on line <b>631</b><br />
<br />

**Comment by Ballbump** [comment]
Same here. This issue results from an outdated package "dompdf" (0.8.2). If you manually update this package to 0.8.4, task2pdf will work fine again. You can find dompdf here on GitHub:
https://github.com/dompdf/dompdf

**Comment by creecros** [comment]
If someone updates the package and PR, I'll merge.

**Comment by Ballbump** [comment]
Unfortunatly, my GitHub-level is "consumer". Don't know what to do.

**Comment by creecros** [comment]
updated the dompdf library to 0.8.5
https://github.com/creecros/Task2pdf/tree/1.3.0
