### ISSUE TITLE
did not work wir german Umlauts

### ISSUE THREAD

**Issue by Lethert** [creecros/Task2pdf#13]
like öäü ÖÄÜ ß

**Comment by Ballbump** [comment]
Sorry, can't confirm. Never had this problem, tested a few minutes ago, everthing fine with our umlauts.

**Comment by creecros** [comment]
Make sure you turn OFF CJK support, as that font set probably does not support Umlauts.

**Comment by Lethert** [comment]
Thanks, 
 
with this setting the PDF-Creation works fine.
 
Mit freundlichen Grüßen
 
Willi Lethert
Kölner Str. 100, 53913 Swisttal
Telefon: +49 (2254) 84 46 47
Mobil: +49 (1782) 84 46 47
E-Mail: Willi@Lethert.de 
 
 
Von: Craig Crosby <notifications@github.com> 
Gesendet: Sonntag, 2. Februar 2020 17:56
An: creecros/Task2pdf <task2pdf@noreply.github.com>
Cc: Lethert <w.lethert@lcs-heimerzheim.de>; Author <author@noreply.github.com>
Betreff: Re: [creecros/Task2pdf] did not work wir german Umlauts (#13)
 
Make sure you turn OFF CJK support, as that font set probably does not support Umlauts.
