### ISSUE TITLE
How to install on debian with the kanboad user interface ?

### ISSUE THREAD

**Issue by jmgway** [creecros/Task2pdf#19]
![2022-04-11_11h25_26](https://user-images.githubusercontent.com/85384969/162709083-12a40fee-f1b4-4915-a316-21a72e45495a.png)
Hello

http://myserver:myport/?controller=PluginController&action=directory

displays the available plugins. When I try to install Task2PDF, there is an error : Unable to download plugin archive.

How can I install it with another method ? Thank you !

![2022-04-11_11h23_21](https://user-images.githubusercontent.com/85384969/162708910-8fab85db-7a56-4e13-951c-0e0d33a7243a.png)

**Comment by creecros** [comment]
that sounds like an issue on your end.
try the kanboard forums.

**Comment by Jieiku** [comment]
Yep, installed fine for me, probably a folder permissions problem for the plugins folder, but hard to say for sure, definitely not a problem with the plugin, it is possible to manually down and install plugins, you can probably find that info on the kanboard forums.
