### ISSUE TITLE
Error generation PDfs with kanboard / Deprecated: htmlspecialchars(): Passing null to parameter #1 ($string) of type string is deprecated in /var/www/app/plugins/MarkdownPlus/Helper/MarkdownPlusHelper.php on line 34

### ISSUE THREAD

**Issue by hattmann** [creecros/Task2pdf#26]
Deprecated: htmlspecialchars(): Passing null to parameter #1 ($string) of
type string is deprecated in
/var/www/app/plugins/MarkdownPlus/Helper/MarkdownPlusHelper.php
on line 34

![image](https://user-images.githubusercontent.com/4472613/202464207-8216ebe6-f2e5-4966-bffd-24b4f999c3dc.png)

Running kanboard with the newest docker image

**Comment by creecros** [comment]
https://github.com/creecros/MarkdownPlus/commit/cb4e790b1ffe6cfd4c384be3755c88edf19e8c83

Upgrade Markdown plus, use the master repo until i get a chance to update the release.

**Comment by creecros** [comment]
https://github.com/kanboard/website/pull/374

once merged, you can just update Markdown plus from KB plugin directory

**Comment by hattmann** [comment]
Thank you very much, now everything works as expected!

**Comment by creecros** [comment]
ya, i noticed that error a couple weeks ago and just forgot to update the release.
