### ISSUE TITLE
MetaMagik custom field destroys layout

### ISSUE THREAD

**Issue by JustFxDev** [creecros/Task2pdf#27]
Hi creecros,

when i print a task with Task2pdf the while having metafields in that task from the MetaMagik plugin i get a "destroyed" Output:

![grafik](https://user-images.githubusercontent.com/82320201/211147029-2b97a2e4-37c8-4541-b0d3-bccc8234c849.png)
.
.
.
.
.
**The task view display is as follows:**
.
.

![grafik](https://user-images.githubusercontent.com/82320201/211147071-98ef77e3-796e-4354-887f-d4107f0961f9.png)

**Comment by creecros** [comment]
same as #9

**Comment by JustFxDev** [comment]
Sorry, i missed that. Well i wil have a closer look on the printlayout. If i can figure out something i will provide a pull request.

Thanks!

Cheers, Fx
