### ISSUE TITLE
Font not found issue

### ISSUE THREAD

**Issue by samjunction** [creecros/Task2pdf#29]
Hi,

Starting from version 1.3.0 to latest I keep getting error "Internal Error: Font not found in:". Only version that seems to be working is Task2pdf-1.2.1

**Comment by creecros** [comment]
that's fairly vague.

**Comment by samjunction** [comment]
I have confirmed again and version 1.3.0 works fine for me and from version 1.4.0 on wards it is giving  Internal Error: Font not found in: C:\Users\kanboard\AppData\Local\Temp/DejaVuSans.ttf.tmp.63c68b4938e34 error.

**Comment by creecros** [comment]
that's better. 

I would try self installing the font, see if that works.

https://dejavu-fonts.github.io/

in the mean time, can you tell me a bit about your configuration, server?

**Comment by samjunction** [comment]
> that's better.
> 
> I would try self installing the font, see if that works.
> 
> https://dejavu-fonts.github.io/
> 
> in the mean time, can you tell me a bit about your configuration, server?

1. Installing font did not work.
2. Kanboard is running IIS 7.5 on Windows 2008 R2
3. PHP version 7.4

**Comment by creecros** [comment]
it's making no sense. I'll have to think about this one, as I don't really have a way to test in a windows environment. 

try this:
go to the config, and turn off the option to embed. it's the only thing I can think of at this moment, as it was the only option added from 1.4.0

**Comment by creecros** [comment]
well, 1 other thing i am noticing is in the error:
`C:\Users\kanboard\AppData\Local\Temp/DejaVuSans.ttf.tmp.63c68b4938e34`

which brings me back to windows, as obviously the forward slash is an issue.

and it appears the rest of the community is having said issue:
https://github.com/dompdf/dompdf/issues/1260

Read through some of those solutions and see if that helps you. It's not looking like there is a solution on my end, but I will keep digging.

**Comment by samjunction** [comment]
Font not found error does not come  if $isFontSubsettingEnabled is set to "false" in Task2pdf\vendor\dompdf\dompdf\src\Options.php

**Comment by creecros** [comment]
https://github.com/creecros/Task2pdf/commit/5f7c04a4e149fb4b18c9d976f7028e0a16b50a8f

give this a try, i updated dompdf library...worth a shot

**Comment by samjunction** [comment]
Hi,

Same thing happened with the new update($isFontSubsettingEnabled set to
true).

Setting $isFontSubsettingEnabled to false works fine.

**Comment by creecros** [comment]
awesome, at least you have a solution.

**Comment by samjunction** [comment]
Hi,

Custom Fields not showing properly in pdf

**Comment by creecros** [comment]
See #9

**Comment by samjunction** [comment]
Thanks

**Comment by samjunction** [comment]
Hi,

I am new to php and kanboard plugin system. I would appreciate if you can
guide me how hook are defined or how can we create new hook and layout for
metamagik

$this->hook->render('template:task:details:bottom', array('task' => $task))

**Comment by samjunction** [comment]
I think i found it. it would use MetaMagik\Template\task\metasummary.php to
print custom fields part.

**Comment by creecros** [comment]
that and metatable.php

**Comment by samjunction** [comment]
Thanks, I'll check it out.

**Comment by samjunction** [comment]
Hi,

Did minor change in MetaMagik\Export\MetaTaskExport.php

See attached screenshot.

**Comment by creecros** [comment]
screenshots don't work from email.

**Comment by samjunction** [comment]
PDF attached

**Comment by creecros** [comment]
you seemed to miss the point. stop responding via email if you want to show anything.
