### ISSUE TITLE
Screenshot .png does not appear in PDF

### ISSUE THREAD

**Issue by frakman1** [creecros/Task2pdf#3]
I attached a screenshot to my task that I was expecting to see in the generated PDF file based on the screenshot of your README (the blue rose). Unfortunately it did not appear in my PDF.

Task view:

![image](https://user-images.githubusercontent.com/5826484/48958577-02d75280-ef2e-11e8-8487-ac0bc291fbf5.png)

I am not sure if this was the intent behind the PDF or not.

**Comment by creecros** [comment]
It does not print attachments, it simply lists file attachments. If you want the image to print like in the readme, it needs to be a linked image in the description.

**Comment by creecros** [comment]
I will look into the possibility though...lots on my plate at the moment.

**Comment by creecros** [comment]
files now have option to be embedded,  so this is solved.
