### ISSUE TITLE
[Feature Request] Include Task attachments in generated PDF

### ISSUE THREAD

**Issue by frakman1** [creecros/Task2pdf#4]
Make the generated PDF include a link to all the attachments. 

The idea would be for the PDF to be self-contained and include everything in the task including all attachments.

**Comment by frakman1** [comment]
It `lists` the attachments but it doesn't `include` them. From [Adobe's help pages](https://helpx.adobe.com/acrobat/using/links-attachments-pdfs.html): 

![image](https://user-images.githubusercontent.com/5826484/48962112-86eb0380-ef49-11e8-902c-9241328b7f7c.png)

The idea is that a single pdf file will include the attachments (not just their names). That way, I can give that pdf to someone and they will also have all the attachments as part of that pdf. 

Make sense?

**Comment by creecros** [comment]
I understand now, I'll have to look into that, not sure on possibility.

**Comment by creecros** [comment]
Dompdf, the library this plug in is using to generate pdfs, does not support that. I would have to use a different library. I'll put on my to do list, but not sure when I might get back to it, maybe a rainy day. My intent with this, was only to create a simple printable pdf, so that a task could be printed out on paper and communicated to someone.

**Comment by frakman1** [comment]
Understood. Not all features are feasible. I get it.
Thank you for looking into it and of course for implementing this plugin in the first place.

**Comment by rimeno** [comment]
Good news, Dompdf can attach file now : https://github.com/dompdf/dompdf/issues/2111

**Comment by creecros** [comment]
I stopped maintaining this plugin, but it looks like my last maintenance included this updated version of dompdf. if it is simple enough, and doesn't require me to spend too much time, ill see if I can implement the usage.

**Comment by rimeno** [comment]
Sorry, I didn't saw that… Thank you for your plugin and your time…

**Comment by creecros** [comment]
https://github.com/creecros/Task2pdf/commit/d8d785092eef12555699c6ca80a8eb1fa11632a2

Try it out and let me know if you have any issues. I tested with an embeded PDF and PNG, both worked.

@rimeno @frakman1

**Comment by frakman1** [comment]
It works now. Thank you so much! 
I created a test task and attached a couple of files and was able to create a PDF from it. I had to open it in Adobe Acrobat to actually view the attachments (Preview app for Mac won't show the attachments)

![image](https://user-images.githubusercontent.com/5826484/104390038-c6e71900-550a-11eb-8ff6-6101029f5937.png)

![image](https://user-images.githubusercontent.com/5826484/104390020-c0f13800-550a-11eb-8994-3b636167113a.png)

**Comment by rimeno** [comment]
Thanks ! It's working, but with some accents problems in attached files.

![Task2pdf_accents](https://user-images.githubusercontent.com/32952122/104428337-a6f43b80-5584-11eb-96c3-21bfb8d7d270.png)

It is not a big issue.

**Comment by creecros** [comment]
ya, im not sure I would even know where to begin to fix that.

**Comment by creecros** [comment]
https://github.com/creecros/Task2pdf/releases/tag/1.4.0
 new release, if you are using this plugin, i recomend the actual release verse the previous test version, i made a few more updates, and included this feature as an option, so it can be turned off or on.
