### ISSUE TITLE
Print all Task of a Project

### ISSUE THREAD

**Issue by aalmir** [creecros/Task2pdf#6]
Would be great if it is possible to print all Task's in one PDF with one click.

**Comment by creecros** [comment]
Interesting idea. I'll see what that entails. All tasks in a project? Or all tasks period?

**Comment by aalmir** [comment]
For my need, it would be all Task's of a project, because we have to archive (Records management) this information. But some GUI to decide which task would be also great.

**Comment by creecros** [comment]
All tasks in a project would make sense to me.

**Comment by aalmir** [comment]
Sounds greats, thanks.

**Comment by creecros** [comment]
@aalmir 
Feel free to test it out, will print all "open" tasks in a project:
https://github.com/creecros/Task2pdf/tree/print_project

the option will be in the project dropdown:
![image](https://user-images.githubusercontent.com/26339368/56245029-5a589500-606c-11e9-85f3-af77617d9219.png)

I still need to brush things up and it won't currently work with CJK support turned on, but it shouldn't take too long for me to complete.

**Comment by creecros** [comment]
all set:
https://github.com/creecros/Task2pdf/releases/tag/1.2.0

**Comment by aalmir** [comment]
Thank you works fine for me.
