### ISSUE TITLE
MetaData not aligned properly

### ISSUE THREAD

**Issue by sankethpb** [creecros/Task2pdf#9]
The Metadata is not aligned properly in the printed PDF. Could you please this?

![image](https://user-images.githubusercontent.com/16034868/61023237-ba8a7900-a3c6-11e9-9d2a-2b789b66387c.png)

Thanks in advance

**Comment by spacecabbie** [comment]
Is there any update on this ?
also is it posible to exclude the custom field Value ? Or meta magik.
Or rename them.
If someone can point out where its done in the code I can have a look to see if i can change it.

**Comment by creecros** [comment]
I do not intend to do anything with this plugin, probably, ever again. But, all the layouts are in one folder, you can edit them. I am willing to add collaborators to this project to help maintain it, but I believe I have done my part, and do not have the time for this plugin any more.

https://github.com/creecros/Task2pdf/tree/master/Template/printlayout

The two main layouts are the ones titled printlayout*.*, one for normal use and the other for cjk support.

Remove the hook from the details.php template to remove meta magik from the layout, be advised, anything else attached to that hook will also disappear from the print layout. If you want to just modify it, you would need to add a layout, specfic for meta magik to override the normal one in the print layout creation stage. This gets a little more complicated for a beginner, but if you understand hooks, then it should make complete sense. In a nutshell, you would create a new hook, remove the current hook, and attach a new layout for metamagik with your modifications to the newly named hook. this will cause Task2PDF to use your metamagik layout and not the one that is part of metamagik when it creates the PDF.

**Comment by spacecabbie** [comment]
> I do not intend to do anything with this plugin, probably, ever again. But, all the layouts are in one folder, you can edit them. I am willing to add collaborators to this project to help maintain it, but I believe I have done my part, and do not have the time for this plugin any more.
> 
> https://github.com/creecros/Task2pdf/tree/master/Template/printlayout
> 
> The two main layouts are the ones titled printlayout*.*, one for normal use and the other for cjk support.
> 
> Remove the hook from the details.php template to remove meta magik from the layout, be advised, anything else attached to that hook will also disappear from the print layout. If you want to just modify it, you would need to add a layout, specfic for meta magik to override the normal one in the print layout creation stage. This gets a little more complicated for a beginner, but if you understand hooks, then it should make complete sense. In a nutshell, you would create a new hook, remove the current hook, and attach a new layout for metamagik with your modifications to the newly named hook. this will cause Task2PDF to use your metamagik layout and not the one that is part of metamagik when it creates the PDF.

Fair enough i'll give it a go then see what i can make although i am pretty n00b programmer so if you be willing to lay down some guidelines ?

I am indeed not familiar with hooks well i understand the principle.
I'll see if i can locate the variables I'll then create a new template file where i specify all printed options and that way its easier editable.  

If any suggestions or tips do let me know.

**Comment by creecros** [comment]
You will need to update both MetaMagik and Task2pdf for these to work.
